 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.4 Build 241129
//-----------------------------------------------------------------------------
#ifndef __GPIO_H
#define __GPIO_H

#include "ht32.h"

//-----------------------------------------------------------------------------

#define IN_PD1_PORT           D
#define IN_PD1_PIN            1
#define IN_PD1_GPIO_CLK      STRCAT2(P,          IN_PD1_PORT)
#define IN_PD1_GPIO_ID       STRCAT2(GPIO_P,     IN_PD1_PORT)
#define IN_PD1_GPIO_PORT     STRCAT2(HT_GPIO,    IN_PD1_PORT)
#define IN_PD1_GPIO_PIN      STRCAT2(GPIO_PIN_,  IN_PD1_PIN)
#define IN_PD1_AFIO_MODE     (AFIO_MODE_GPIO)
#define IN_PD1_STATE         (GPIO_ReadInBit(IN_PD1_GPIO_PORT, IN_PD1_GPIO_PIN))



//-----------------------------------------------------------------------------
#define OUT_PA6_PORT           A
#define OUT_PA6_PIN            6
#define OUT_PA6_GPIO_CLK      STRCAT2(P,          OUT_PA6_PORT)
#define OUT_PA6_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA6_PORT)
#define OUT_PA6_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA6_PORT)
#define OUT_PA6_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA6_PIN)
#define OUT_PA6_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA6_HIGH          OUT_PA6_GPIO_PORT->SRR    = OUT_PA6_GPIO_PIN
#define OUT_PA6_LOW           OUT_PA6_GPIO_PORT->RR     = OUT_PA6_GPIO_PIN
#define OUT_PA6_XOR           OUT_PA6_GPIO_PORT->DOUTR ^= OUT_PA6_GPIO_PIN
//-----------------------------------------------------------------------------

#define OUT_PA0_PORT           A
#define OUT_PA0_PIN            0
#define OUT_PA0_GPIO_CLK      STRCAT2(P,          OUT_PA0_PORT)
#define OUT_PA0_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA0_PORT)
#define OUT_PA0_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA0_PORT)
#define OUT_PA0_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA0_PIN)
#define OUT_PA0_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA0_HIGH          OUT_PA0_GPIO_PORT->SRR    = OUT_PA0_GPIO_PIN
#define OUT_PA0_LOW           OUT_PA0_GPIO_PORT->RR     = OUT_PA0_GPIO_PIN
#define OUT_PA0_XOR           OUT_PA0_GPIO_PORT->DOUTR ^= OUT_PA0_GPIO_PIN

#define OLED_SCL_PORT           A
#define OLED_SCL_PIN            0
#define OLED_SCL_GPIO_CLK      STRCAT2(P,          OLED_SCL_PORT)
#define OLED_SCL_GPIO_ID       STRCAT2(GPIO_P,     OLED_SCL_PORT)
#define OLED_SCL_GPIO_PORT     STRCAT2(HT_GPIO,    OLED_SCL_PORT)
#define OLED_SCL_GPIO_PIN      STRCAT2(GPIO_PIN_,  OLED_SCL_PIN)
#define OLED_SCL_AFIO_MODE     (AFIO_MODE_GPIO)
#define OLED_SCL_HIGH          OLED_SCL_GPIO_PORT->SRR    = OLED_SCL_GPIO_PIN
#define OLED_SCL_LOW           OLED_SCL_GPIO_PORT->RR     = OLED_SCL_GPIO_PIN
#define OLED_SCL_XOR           OLED_SCL_GPIO_PORT->DOUTR ^= OLED_SCL_GPIO_PIN

#define OUT_PA1_PORT           A
#define OUT_PA1_PIN            1
#define OUT_PA1_GPIO_CLK      STRCAT2(P,          OUT_PA1_PORT)
#define OUT_PA1_GPIO_ID       STRCAT2(GPIO_P,     OUT_PA1_PORT)
#define OUT_PA1_GPIO_PORT     STRCAT2(HT_GPIO,    OUT_PA1_PORT)
#define OUT_PA1_GPIO_PIN      STRCAT2(GPIO_PIN_,  OUT_PA1_PIN)
#define OUT_PA1_AFIO_MODE     (AFIO_MODE_GPIO)
#define OUT_PA1_HIGH          OUT_PA1_GPIO_PORT->SRR    = OUT_PA1_GPIO_PIN
#define OUT_PA1_LOW           OUT_PA1_GPIO_PORT->RR     = OUT_PA1_GPIO_PIN
#define OUT_PA1_XOR           OUT_PA1_GPIO_PORT->DOUTR ^= OUT_PA1_GPIO_PIN

#define OLED_SDA_PORT           A
#define OLED_SDA_PIN            1
#define OLED_SDA_GPIO_CLK      STRCAT2(P,          OLED_SDA_PORT)
#define OLED_SDA_GPIO_ID       STRCAT2(GPIO_P,     OLED_SDA_PORT)
#define OLED_SDA_GPIO_PORT     STRCAT2(HT_GPIO,    OLED_SDA_PORT)
#define OLED_SDA_GPIO_PIN      STRCAT2(GPIO_PIN_,  OLED_SDA_PIN)
#define OLED_SDA_AFIO_MODE     (AFIO_MODE_GPIO)
#define OLED_SDA_HIGH          OLED_SDA_GPIO_PORT->SRR    = OLED_SDA_GPIO_PIN
#define OLED_SDA_LOW           OLED_SDA_GPIO_PORT->RR     = OLED_SDA_GPIO_PIN
#define OLED_SDA_XOR           OLED_SDA_GPIO_PORT->DOUTR ^= OLED_SDA_GPIO_PIN



//-----------------------------------------------------------------------------
void GPIO_Configuration(void);

#endif

