 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.4 Build 241129
//-----------------------------------------------------------------------------
#include "USART0.h"
#include <string.h>
#include "ATGM336H.h"
//-----------------------------------------------------------------------------
__ALIGN4 _USART0_STRUCT rxd_scomm0;
__ALIGN4 _USART0_STRUCT txd_scomm0;

bool ATGM_AnalyseBufferReady = false;

//-----------------------------------------------------------------------------
void USART0_Configuration(void)
{
  USART_InitTypeDef USART_InitStruct;
  CKCU_PeripClockConfig_TypeDef CKCUClock = {{0}};
  CKCUClock.Bit.USART0   = 1;
  CKCUClock.Bit.AFIO     = 1;
  CKCUClock.Bit.PA      = 1;
  CKCU_PeripClockConfig(CKCUClock, ENABLE);

  GPIO_PullResistorConfig(HT_GPIOA, GPIO_PIN_3, GPIO_PR_UP);  //Turn on UxART Rx internal pull up resistor to prevent unknow state

  AFIO_GPxConfig(GPIO_PA, AFIO_PIN_2, AFIO_FUN_USART_UART);  // Config AFIO mode
  AFIO_GPxConfig(GPIO_PA, AFIO_PIN_3, AFIO_FUN_USART_UART);  // Config AFIO mode

  USART_InitStruct.USART_BaudRate = 9600;
  USART_InitStruct.USART_WordLength = USART_WORDLENGTH_8B;
  USART_InitStruct.USART_StopBits = USART_STOPBITS_1;
  USART_InitStruct.USART_Parity = USART_PARITY_NO;
  USART_InitStruct.USART_Mode = USART_MODE_NORMAL;
  USART_Init(HT_USART0, &USART_InitStruct);
  USART_RxCmd(HT_USART0, ENABLE);
  USART_TxCmd(HT_USART0, ENABLE);

  USART_IntConfig(HT_USART0, USART_INT_RXDR, ENABLE);

  NVIC_EnableIRQ(USART0_IRQn);
  USART0_init_buffer();
}

//-----------------------------------------------------------------------------
void USART0_init_buffer (void)
{
  rxd_scomm0.read_pt = 0;
  rxd_scomm0.write_pt = 0;
  rxd_scomm0.cnt = 0;

  txd_scomm0.read_pt = 0;
  txd_scomm0.write_pt = 0;
  txd_scomm0.cnt = 0;
}

void USART0_ClearBuffer(void) {
	USART0_init_buffer();
	memset(rxd_scomm0.buffer, 0, sizeof(rxd_scomm0.buffer));
}

//-----------------------------------------------------------------------------
void USART0_IRQHandler(void)
{
  // Tx, move data from buffer to UART FIFO
  if ((HT_USART0->SR) & USART_FLAG_TXC)
  {
    if (!txd_scomm0.cnt)
    {
      USART_IntConfig(HT_USART0, USART_INT_TXC, DISABLE);
    }
    else
    {
      u16 i;
      for (i = 0; i < USART0_FIFO_LEN; i++)   //have FIFO?
      {
        USART_SendData(HT_USART0, txd_scomm0.buffer[txd_scomm0.read_pt]);
        txd_scomm0.read_pt = (txd_scomm0.read_pt + 1) % USART0_BUF_SIZE;
        txd_scomm0.cnt--;
        if (!txd_scomm0.cnt)
          break;
      }
    }
  }

  // Rx, move data from UART FIFO to buffer
  if ((HT_USART0->SR) & USART_FLAG_RXDR)
  {
    rxd_scomm0.buffer[rxd_scomm0.write_pt] = USART_ReceiveData(HT_USART0);

    rxd_scomm0.write_pt = (rxd_scomm0.write_pt + 1) % USART0_BUF_SIZE;
    rxd_scomm0.cnt++;
  }
  char* ret1 = strstr((char*)rxd_scomm0.buffer, "$BDGSV");		// 查找$GNRMC前一条
  char* ret2 = strstr((char*)rxd_scomm0.buffer, "$GNVTG");		// 查找$GNRMC后一条，如果$GNVTG和￥BDGSV都收到了，那么$GNRMC肯定收到了
  
  if (ret1 != NULL && ret2 != NULL)
  {
	
	strcpy(ATGM_AnalyseBuffer, (char*)rxd_scomm0.buffer);
//	printf("%s\r\n", ATGM_AnalyseBuffer);
	USART0_ClearBuffer();
	ATGM_AnalyseBufferReady = true;
  }
  
}



//void USART0_IRQHandler(void) {	
//	u8 data;
//	
//	if (USART_GetFlagStatus(HT_USART0, USART_FLAG_RXDR))
//	{
//		data = USART_ReceiveData(HT_USART0);
//		
//		printf("%c", data);
//	}
//}

//-----------------------------------------------------------------------------
void USART0_analyze_data(void)
{
  u8 tmp;
  if(!rxd_scomm0.cnt)
    return;

  //...to be add
  tmp = rxd_scomm0.buffer[rxd_scomm0.read_pt];
  if( (tmp != 0xAA) )            //for example
  {
    NVIC_DisableIRQ(USART0_IRQn);
    rxd_scomm0.cnt--;  //throw invalid data
    NVIC_EnableIRQ(USART0_IRQn);
    rxd_scomm0.read_pt = (rxd_scomm0.read_pt + 1) % USART0_BUF_SIZE;
    return;
  }
  else if(rxd_scomm0.cnt >= 8)    //for example
  {
    //add your code here

  }
}

//-----------------------------------------------------------------------------
void USART0_tx_data(u8 *pt, u8 len)
{
  while(len--)
  {
    txd_scomm0.buffer[txd_scomm0.write_pt] = *pt++;
    txd_scomm0.write_pt = (txd_scomm0.write_pt + 1) % USART0_BUF_SIZE;
    NVIC_DisableIRQ(USART0_IRQn);
    txd_scomm0.cnt++;
    NVIC_EnableIRQ(USART0_IRQn);
  }

  if(txd_scomm0.cnt)
    USART_IntConfig(HT_USART0,  USART_INT_TXC , ENABLE);
}

//-----------------------------------------------------------------------------
void USART0_test(void)
{
  u8 i,test_array[8];
  for(i=0; i<8; i++)
  {
    test_array[i] = i;
  }
  USART0_tx_data(test_array, 8);
}

//-----------------------------------------------------------------------------


