 /************************************************************************************************************
 * @attention
 *
 * Firmware Disclaimer Information
 *
 * 1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, which is supplied by Holtek Semiconductor Inc., (hereinafter referred to as "HOLTEK") is the
 *    proprietary and confidential intellectual property of HOLTEK, and is protected by copyright law and
 *    other intellectual property laws.
 *
 * 2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *    code, is confidential information belonging to HOLTEK, and must not be disclosed to any third parties
 *    other than HOLTEK and the customer.
 *
 * 3. The program technical documentation, including the code, is provided "as is" and for customer reference
 *    only. After delivery by HOLTEK, the customer shall use the program technical documentation, including
 *    the code, at their own risk. HOLTEK disclaims any expressed, implied or statutory warranties, including
 *    the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 * <h2><center>Copyright (C) Holtek Semiconductor Inc. All rights reserved</center></h2>
 ************************************************************************************************************/
//Generated by HT32CodeConfig V1.1.4 Build 241129
//-----------------------------------------------------------------------------
#ifndef __USART1_H
#define __USART1_H


//-----------------------------------------------------------------------------
#include "ht32.h"
#include <string.h>
//-----------------------------------------------------------------------------
#define USART1_BUF_SIZE 256
#define USART1_FIFO_LEN 1

//-----------------------------------------------------------------------------
typedef struct
{
  u8 buffer[USART1_BUF_SIZE];
  u16 write_pt;
  u16 read_pt;
  u16 cnt;
}_USART1_STRUCT;

extern __ALIGN4 _USART1_STRUCT rxd_scomm1;
extern __ALIGN4 _USART1_STRUCT txd_scomm1;

//-----------------------------------------------------------------------------
void USART1_Configuration(void);
void USART1_init_buffer (void);
void USART1_analyze_data(void);
void USART1_tx_data(u8 *pt, u8 len);
void USART1_test(void);
void USART1_ClearBuffer(void);
void USART1_SendByte(u8 byte);
void USART1_SendArray(u8* Array, uint16_t Length);
//-----------------------------------------------------------------------------
#endif

